# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wileyswikit/Projects/VoxelEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wileyswikit/Projects/VoxelEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wileyswikit/Projects/VoxelEngine/CMakeFiles /Users/wileyswikit/Projects/VoxelEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wileyswikit/Projects/VoxelEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named VoxelEngine

# Build rule for target.
VoxelEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VoxelEngine
.PHONY : VoxelEngine

# fast build rule for target.
VoxelEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/build
.PHONY : VoxelEngine/fast

src/AsyncCircularQueue.o: src/AsyncCircularQueue.cpp.o
.PHONY : src/AsyncCircularQueue.o

# target to build an object file
src/AsyncCircularQueue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/AsyncCircularQueue.cpp.o
.PHONY : src/AsyncCircularQueue.cpp.o

src/AsyncCircularQueue.i: src/AsyncCircularQueue.cpp.i
.PHONY : src/AsyncCircularQueue.i

# target to preprocess a source file
src/AsyncCircularQueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/AsyncCircularQueue.cpp.i
.PHONY : src/AsyncCircularQueue.cpp.i

src/AsyncCircularQueue.s: src/AsyncCircularQueue.cpp.s
.PHONY : src/AsyncCircularQueue.s

# target to generate assembly for a file
src/AsyncCircularQueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/AsyncCircularQueue.cpp.s
.PHONY : src/AsyncCircularQueue.cpp.s

src/Block.o: src/Block.cpp.o
.PHONY : src/Block.o

# target to build an object file
src/Block.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/Block.cpp.o
.PHONY : src/Block.cpp.o

src/Block.i: src/Block.cpp.i
.PHONY : src/Block.i

# target to preprocess a source file
src/Block.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/Block.cpp.i
.PHONY : src/Block.cpp.i

src/Block.s: src/Block.cpp.s
.PHONY : src/Block.s

# target to generate assembly for a file
src/Block.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/Block.cpp.s
.PHONY : src/Block.cpp.s

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Chunk.o: src/Chunk.cpp.o
.PHONY : src/Chunk.o

# target to build an object file
src/Chunk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/Chunk.cpp.o
.PHONY : src/Chunk.cpp.o

src/Chunk.i: src/Chunk.cpp.i
.PHONY : src/Chunk.i

# target to preprocess a source file
src/Chunk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/Chunk.cpp.i
.PHONY : src/Chunk.cpp.i

src/Chunk.s: src/Chunk.cpp.s
.PHONY : src/Chunk.s

# target to generate assembly for a file
src/Chunk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/Chunk.cpp.s
.PHONY : src/Chunk.cpp.s

src/Debugging.o: src/Debugging.cpp.o
.PHONY : src/Debugging.o

# target to build an object file
src/Debugging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/Debugging.cpp.o
.PHONY : src/Debugging.cpp.o

src/Debugging.i: src/Debugging.cpp.i
.PHONY : src/Debugging.i

# target to preprocess a source file
src/Debugging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/Debugging.cpp.i
.PHONY : src/Debugging.cpp.i

src/Debugging.s: src/Debugging.cpp.s
.PHONY : src/Debugging.s

# target to generate assembly for a file
src/Debugging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/Debugging.cpp.s
.PHONY : src/Debugging.cpp.s

src/Shader.o: src/Shader.cpp.o
.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i
.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s
.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/TerrainGenerator.o: src/TerrainGenerator.cpp.o
.PHONY : src/TerrainGenerator.o

# target to build an object file
src/TerrainGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/TerrainGenerator.cpp.o
.PHONY : src/TerrainGenerator.cpp.o

src/TerrainGenerator.i: src/TerrainGenerator.cpp.i
.PHONY : src/TerrainGenerator.i

# target to preprocess a source file
src/TerrainGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/TerrainGenerator.cpp.i
.PHONY : src/TerrainGenerator.cpp.i

src/TerrainGenerator.s: src/TerrainGenerator.cpp.s
.PHONY : src/TerrainGenerator.s

# target to generate assembly for a file
src/TerrainGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/TerrainGenerator.cpp.s
.PHONY : src/TerrainGenerator.cpp.s

src/ThreadPool.o: src/ThreadPool.cpp.o
.PHONY : src/ThreadPool.o

# target to build an object file
src/ThreadPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/ThreadPool.cpp.o
.PHONY : src/ThreadPool.cpp.o

src/ThreadPool.i: src/ThreadPool.cpp.i
.PHONY : src/ThreadPool.i

# target to preprocess a source file
src/ThreadPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/ThreadPool.cpp.i
.PHONY : src/ThreadPool.cpp.i

src/ThreadPool.s: src/ThreadPool.cpp.s
.PHONY : src/ThreadPool.s

# target to generate assembly for a file
src/ThreadPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/ThreadPool.cpp.s
.PHONY : src/ThreadPool.cpp.s

src/VoxelEngine.o: src/VoxelEngine.cpp.o
.PHONY : src/VoxelEngine.o

# target to build an object file
src/VoxelEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/VoxelEngine.cpp.o
.PHONY : src/VoxelEngine.cpp.o

src/VoxelEngine.i: src/VoxelEngine.cpp.i
.PHONY : src/VoxelEngine.i

# target to preprocess a source file
src/VoxelEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/VoxelEngine.cpp.i
.PHONY : src/VoxelEngine.cpp.i

src/VoxelEngine.s: src/VoxelEngine.cpp.s
.PHONY : src/VoxelEngine.s

# target to generate assembly for a file
src/VoxelEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/VoxelEngine.cpp.s
.PHONY : src/VoxelEngine.cpp.s

src/World.o: src/World.cpp.o
.PHONY : src/World.o

# target to build an object file
src/World.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/World.cpp.o
.PHONY : src/World.cpp.o

src/World.i: src/World.cpp.i
.PHONY : src/World.i

# target to preprocess a source file
src/World.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/World.cpp.i
.PHONY : src/World.cpp.i

src/World.s: src/World.cpp.s
.PHONY : src/World.s

# target to generate assembly for a file
src/World.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/World.cpp.s
.PHONY : src/World.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... VoxelEngine"
	@echo "... src/AsyncCircularQueue.o"
	@echo "... src/AsyncCircularQueue.i"
	@echo "... src/AsyncCircularQueue.s"
	@echo "... src/Block.o"
	@echo "... src/Block.i"
	@echo "... src/Block.s"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Chunk.o"
	@echo "... src/Chunk.i"
	@echo "... src/Chunk.s"
	@echo "... src/Debugging.o"
	@echo "... src/Debugging.i"
	@echo "... src/Debugging.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/TerrainGenerator.o"
	@echo "... src/TerrainGenerator.i"
	@echo "... src/TerrainGenerator.s"
	@echo "... src/ThreadPool.o"
	@echo "... src/ThreadPool.i"
	@echo "... src/ThreadPool.s"
	@echo "... src/VoxelEngine.o"
	@echo "... src/VoxelEngine.i"
	@echo "... src/VoxelEngine.s"
	@echo "... src/World.o"
	@echo "... src/World.i"
	@echo "... src/World.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

